--NOTE: You should create a database (ie. HouseSalePrice) before running this script. 
--This script is to create all seven tables and insert data into five reference tables (HEATING, LOTSHAPE, NEIGHBORHOOD, GARATETYPE, HOUSETYPE)

--1. CREATE TABLES

DROP TABLE IF EXISTS "LotShape";

CREATE TABLE "LotShape" (
  "id" varchar(10) PRIMARY KEY,
  "lotshape_desc" varchar(100)
);

DROP TABLE IF EXISTS "Neighborhood" CASCADE;

CREATE TABLE "Neighborhood" (
  "id" varchar(10) PRIMARY KEY,
  "neighborhood_name" varchar(100)
);

DROP TABLE IF EXISTS "HouseType" CASCADE;

CREATE TABLE "HouseType" (
  "id" varchar(10) PRIMARY KEY,
  "desc" varchar(100)
);

DROP TABLE IF EXISTS "Heating" CASCADE;

CREATE TABLE "Heating" (
  "id" varchar(10) PRIMARY KEY,
  "desc" varchar(100)
);

DROP TABLE IF EXISTS "GarageType" CASCADE;

CREATE TABLE "GarageType" (
  "id" varchar(10) PRIMARY KEY,
  "desc" varchar(100)
);

DROP TABLE IF EXISTS "HouseSaleHistory" CASCADE;

CREATE TABLE "HouseSaleHistory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lotarea" numeric,
  "lotshape" varchar(10),
  "neighborhood" varchar(10),
  "housetype" varchar(10),
  "yearbuilt" numeric,
  "yearremoadd" numeric,
  "heating" varchar(10),
  "totalhousesqft" numeric,
  "fullbath" int,
  "halfbath" int,
  "bedroom" int,
  "fireplaces" boolean,
  "garagetype" varchar(10),
  "garagecar" int,
  "paveddrive" boolean,
  "poolarea" boolean,
  "yearsold" date,
  "saleprice" numeric
);

DROP TABLE IF EXISTS "HouseSalePrediction" CASCADE;

CREATE TABLE "HouseSalePrediction" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lotarea" numeric,
  "lotshape" varchar(10),
  "neighborhood" varchar(10),
  "housetype" varchar(10),
  "yearbuilt" numeric,
  "yearremoadd" numeric,
  "heating" varchar(10),
  "totalhousesqft" numeric,
  "fullbath" int,
  "halfbath" int,
  "bedroom" int,
  "fireplaces" boolean,
  "garagetype" varchar(10),
  "garagecar" int,
  "paveddrive" boolean,
  "poolarea" boolean,
  "yearsold" date,
  "salepriceprediction" numeric
);

ALTER TABLE "HouseSaleHistory" ADD FOREIGN KEY ("lotshape") REFERENCES "LotShape" ("id");

ALTER TABLE "HouseSaleHistory" ADD FOREIGN KEY ("neighborhood") REFERENCES "Neighborhood" ("id");

ALTER TABLE "HouseSaleHistory" ADD FOREIGN KEY ("housetype") REFERENCES "HouseType" ("id");

ALTER TABLE "HouseSaleHistory" ADD FOREIGN KEY ("heating") REFERENCES "Heating" ("id");

ALTER TABLE "HouseSaleHistory" ADD FOREIGN KEY ("garagetype") REFERENCES "GarageType" ("id");

ALTER TABLE "HouseSalePrediction" ADD FOREIGN KEY ("lotshape") REFERENCES "LotShape" ("id");

ALTER TABLE "HouseSalePrediction" ADD FOREIGN KEY ("neighborhood") REFERENCES "Neighborhood" ("id");

ALTER TABLE "HouseSalePrediction" ADD FOREIGN KEY ("housetype") REFERENCES "HouseType" ("id");

ALTER TABLE "HouseSalePrediction" ADD FOREIGN KEY ("heating") REFERENCES "Heating" ("id");

ALTER TABLE "HouseSalePrediction" ADD FOREIGN KEY ("garagetype") REFERENCES "GarageType" ("id");


--2. INSERT DATA INTO REFERENCE TABLES

insert into "GarageType" values('2Types', 'More than one type of garage');
insert into "GarageType" values('Attchd', 'Attached to home');
insert into "GarageType" values('Basment', 'Basement Garage');
insert into "GarageType" values('BuiltIn', 'Built-In (Garage part of house - typically has room above garage');
insert into "GarageType" values('CarPort', 'Car Port');
insert into "GarageType" values('Detchd', 'Detached from home');
insert into "GarageType" values('No Garage', 'No Garage');

insert into "Heating" values('Floor', 'Floor Furnace');
insert into "Heating" values('GasA', 'Gas forced warm air furnace');
insert into "Heating" values('GasW', 'Gas hot water or steam heat');
insert into "Heating" values('Grav', 'Gravity furnace');
insert into "Heating" values('OthW', 'Hot water or steam heat other than gas');
insert into "Heating" values('Wall', 'Wall furnace');

insert into "HouseType" values('1story', 'One Story');
insert into "Heating" values('1.5Fin', 'One and one-half story: 2nd level finished');
insert into "HouseType" values('1.5Unf', 'One and one-half story: 2nd level unfinished');
insert into "Heating" values('2Story', 'Two story');
insert into "HouseType" values('2.5Fin', 'Two and one-half story: 2nd level finished');
insert into "Heating" values('2.5Unf', 'Two and one-half story: 2nd level unfinished');
insert into "HouseType" values('SFoyer', 'Split Foyer');
insert into "Heating" values('SLvl', 'Split Level');

insert into "LotShape" values('Reg', 'Regular');
insert into "LotShape" values('IR1', 'Slightly irregular');
insert into "LotShape" VALUES('IR2', 'Moderately Irregular');
insert into "LotShape" values('IR3', 'Irregular');

insert into "Neighborhood" values('Blmngtn', 'Bloomington Heights');
insert into "Neighborhood" values('Blueste', 'Bluestem');
insert into "Neighborhood" values('BrDale', 'Briardale');
insert into "Neighborhood" values('BrkSide', 'Brookside');
insert into "Neighborhood" values('ClearCr', 'Clear Creek');
insert into "Neighborhood" values('CollgCr', 'College Creek');
insert into "Neighborhood" values('Crawfor', 'Crawford');
insert into "Neighborhood" values('Edwards', 'Edwards');
insert into "Neighborhood" values('Gilbert', 'Gilbert');
insert into "Neighborhood" values('IDOTRR', 'Iowa DOT and Rail Road');
insert into "Neighborhood" values('MeadowV', 'Meadow Village');
insert into "Neighborhood" values('Mitchel', 'Mitchell');
insert into "Neighborhood" values('Names', 'North Ames');
insert into "Neighborhood" values('NoRidge', 'Northridge');
insert into "Neighborhood" values('NPkVill', 'Northpark Villa');
insert into "Neighborhood" values('NridgHt', 'Northridge Heights');
insert into "Neighborhood" values('NWAmes', 'Northwest Ames');
insert into "Neighborhood" values('OldTown', 'Old Town');
insert into "Neighborhood" values('SWISU', 'South & West of Iowa State University');
insert into "Neighborhood" values('Sawyer', 'Sawyer');
insert into "Neighborhood" values('SawyerW', 'Sawyer West');
insert into "Neighborhood" values('Somerst', 'Somerset');
insert into "Neighborhood" values('StoneBr', 'Stone Brook');
insert into "Neighborhood" values('Timber', 'Timberland');
insert into "Neighborhood" values('Veenker', 'Veenker');

